development:
  access_key_id: AKIAJWIVG2EY3RU76ETQ
  secret_access_key: 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
  bucket: guiderer_dev

production:
  access_key_id: AKIAJWIVG2EY3RU76ETQ
  secret_access_key: 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
  bucket: guiderer


